<script src="{{ asset('assets/cms/plugins/jquery/jquery-3.5.1.min.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/perfectscroll/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/pace/pace.min.js') }}"></script>
{{-- <script src="{{ asset('assets/cms/plugins/apexcharts/apexcharts.min.js') }}"></script> --}}
<script src="{{ asset('assets/cms/plugins/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('assets/cms/js/main.min.js') }}"></script>
<script src="{{ asset('assets/cms/js/custom.js') }}"></script>
{{-- <script src="{{ asset('assets/cms/js/pages/dashboard.js') }}"></script> --}}
<script src="{{ asset('assets/cms/js/pages/datatables.js') }}"></script>
<script src="https://code.iconify.design/iconify-icon/1.0.0-beta.3/iconify-icon.min.js"></script>
<script src="{{ asset('assets/cms/plugins/select2/js/select2.js') }}"></script>
<script src="{{ asset('assets/cms/js/sweetalert2.all.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/lightbox/fslightbox.js') }}"></script>
<script src="{{ asset('assets/cms/js/jquery.smartWizard.min.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/input-mask/inputmask.js') }}"></script>
<script src="{{ asset('assets/cms/plugins/input-mask/jquery.inputmask.js') }}"></script>